// svelte-kit/src/lib/Button.svelte
<script lang="ts">
	import { handleClick } from 'adjust-core/lib/handleClick.js';

	type Props = {
		onclick?: () => void;
	};
	let { onclick }: Props = $props();

	function Click() {
		console.log('Svelte things');
		handleClick();
		onclick && onclick();
	}
</script>

<button onclick={Click}>Click me</button>

// react/src/components/Button.tsx
import { handleClick } from "adjust-core";
import React from "react";

interface ButtonProps {
  onClick?: () => void;
  children: React.ReactNode;
}

export default function Button({ onClick, children }: ButtonProps) {
  function Click() {
    console.log("react");
    handleClick();
    onClick && onClick();
  }

  return (
    <button
      onClick={Click}
      style={{ padding: "10px 20px", border: "1px solid #ccc" }}
    >
      {children}
    </button>
  );
}
